apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: express-users
  name: express-users
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: express-users
    spec:
      containers:
        - image: jorgefelix11/express-users:chat5
          name: express-users
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
