apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: express-chat
  name: express-chat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: express-chat
    spec:
      containers:
        - image: jorgefelix11/express_chat:chat
          name: express-chat
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
